# Generated by Django 5.1.1 on 2024-10-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inputapp', '0002_remove_students_phno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='age',
            new_name='AGE',
        ),
    ]
