# Generated by Django 5.1.1 on 2024-10-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputapp', '0003_rename_age_students_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('phno', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
