num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
num3 = int(input("Enter the third number: "))
numbers = sorted([num1, num2, num3])
print("The second largest number is:", numbers[1])