# Generated by Django 5.1.1 on 2024-10-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('company', models.CharField(max_length=1000)),
                ('model', models.CharField(max_length=1000)),
                ('colour', models.CharField(max_length=1000)),
                ('cc', models.PositiveIntegerField()),
                ('bhp', models.PositiveIntegerField()),
            ],
        ),
    ]
