# Generated by Django 5.1.1 on 2024-10-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelapp', '0002_bike'),
    ]

    operations = [
        migrations.CreateModel(
            name='anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mc', models.CharField(max_length=100)),
                ('episodes', models.IntegerField()),
            ],
        ),
    ]
